env:
  node: true
  es2020: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: [
    './tsconfig.json',
  ]
  sourceType: 'module'
extends:
  - 'tuxsnct-typescript'
  - "plugin:monorepo/recommended"
plugins:
  - 'monorepo'
rules:
  'no-use-before-define': 0
